### ISSUE TITLE
[FeatureRequest]: Closed Loop - Automatic PID Tuning

### ISSUE THREAD

**Issue by lirwin3007** [dc42/Duet3Expansion#12]
### Is your feature request related to a problem? Please describe.

PID tuning is difficult and can lead to unstable oscillations

### Describe the solution you propose.

An automated PID tuning routine, similar to that we already have for heaters

### Describe alternatives you've considered

Currently we have manual tuning, but that has the issues outlined above

### Provide any additional context or information.

A basic zeiger-nichols manoeuvre was implemented, but is currently not working so is `#if false`d out

**Comment by T3P3** [comment]
Closed as automated PID tuning will be handled but he closed loop plugin and not by expansion board firmware.
