### ISSUE TITLE
iterationMultipler/PhaseIncrement for closed loop basic tuning are meaningless

### ISSUE THREAD

**Issue by nikscha** [dc42/Duet3Expansion#17]
In Duet3Expansion/src/ClosedLoop/Tuning.cpp in line 80/81  iterationMultipler and PhaseIncrement are set, but they cancel out in line 83/84.

iterationMultipler can be 1 or 4, and PhaseIncrement can therefore be either 4 or 16. Either way, NumDummySteps is always 256/4 and NumSamples ia always 4096/4.

**Comment by dc42** [comment]
Thanks for pointing this out. I have committed a change to improve and clarify the code.
