### ISSUE TITLE
[FeatureRequest]: Closed Loop - Additional Tuning Moves

### ISSUE THREAD

**Issue by lirwin3007** [dc42/Duet3Expansion#7]
### Is your feature request related to a problem? Please describe.

Currently some tuning moves are greyed out and unavailable

### Describe the solution you propose.

These tuning moves need writing :tada:

### Describe alternatives you've considered

N/A

### Provide any additional context or information.

The names & nature of each unimplemented tuning move can be found in `src/ClosedLoop/Tuning.cpp`

**Comment by T3P3** [comment]
Probably superseded by the new consolidated tuning moves

**Comment by T3P3** [comment]
closed as no longer required due to new tuning moves:
https://docs.duet3d.com/User_manual/Tuning/Duet_3_1HCL_tuning#runtime-tuning
