### ISSUE TITLE
[FeatureRequest]: Closed Loop - Support currents up to 6.3A

### ISSUE THREAD

**Issue by lirwin3007** [dc42/Duet3Expansion#8]
### Is your feature request related to a problem? Please describe.

Currently the TMCs are limited to 4.5A. However, we should allow a 'peak current' of 6.3A.
Setting a motor current higher than 4.5A is currently not supported.

### Describe the solution you propose.

Support setting a current higher than 4.5A, but don't let this current run continuously. Further discussion is required around the limits here.

### Describe alternatives you've considered

N/A

### Provide any additional context or information.

See https://github.com/Duet3D/Duet3Expansion/blob/0fac927c6fddccb83bd47bcc877e23817f58ac09/src/Config/EXP1HCL.h#L45 for the relevant code

**Comment by T3P3** [comment]
implemented in this commit https://github.com/Duet3D/Duet3Expansion/commit/d1aa1e11034a13adbb99286df9dc4535f085b851
