### ISSUE TITLE
[FeatureRequest]: Closed Loop - Ensure 'forward' is the same in open & closed loop

### ISSUE THREAD

**Issue by lirwin3007** [dc42/Duet3Expansion#9]
### Is your feature request related to a problem? Please describe.

Closed loop control needs to know how the encoder is mounted relative to the motor (i.e. is it on forward or backward)
To find this, it runs a tuning move.
If the encoder is found to be on backwards, the motor is set to run in reverse when in closed loop mode
This means that the 'forward' direction may not be the same in closed and open loop mode

### Describe the solution you propose.

https://github.com/Duet3D/Duet3Expansion/blob/0fac927c6fddccb83bd47bcc877e23817f58ac09/src/ClosedLoop/ClosedLoop.cpp#L1144
should take into account if the encoder is on backwards and run backwards as well if this is the case.

### Describe alternatives you've considered

N/A

### Provide any additional context or information.

N/A

**Comment by T3P3** [comment]
We need to check this is always the case (e.g. with the encoder mounted 180 degrees from the motor - clockwise on the motor would lead to anticlockwise encoder pulses).

**Comment by T3P3** [comment]
needs to be checked with the magnetic encoder

**Comment by dc42** [comment]
Already implemented for quadrature encoders in 3.4 and magnetic encoders in 3.5beta1.
